# Generated by Django 3.2.3 on 2021-06-08 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinclone', '0003_auto_20210608_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
